version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: intermedia_lms
    container_name: intermedia_lms-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - intermedia_lms

  nginx:
    image: nginx:alpine
    container_name: intermedia_lms-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - intermedia_lms

networks:
  intermedia_lms:
    driver: bridge
